language: php
php:
  - 7.0
  - 7.1
matrix:
   fast_finish: true

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - sudo apt-get update -qq
install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script: phpunit -vvv